services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pokemon
    ports:
      - "6543:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: