version: '3'

dotenv: ['.env.local', '.env']

tasks:
  hello:
    cmds:
      - echo 'Hello World from Task!'
    silent: true
  migrate-up:
    cmds:
      - echo 'Migrating up...'
      - migrate -source file://db/migrations -database $POSTGRES_URL up
    silent: true

  migrate-down:
    cmds:
      - echo 'Migrating down...'
      - migrate -source file://db/migrations -database $POSTGRES_URL down
    silent: true

  dump-schema:
    cmds:
      - echo 'Dumping schema...'
      - pg_dump -s $POSTGRES_URL > db/schema.sql
    silent: true

  sqlc-gen:
    cmds:
      - echo 'Generating SQLC...'
      - POSTGRES_URL=$POSTGRES_URL sqlc generate
      - echo $DB_URL
    silent: true