version: '3'

dotenv: ['.env.local', '.env']

tasks:
  hello:
    cmds:
      - echo 'Hello World from Task!'
    silent: true

  db-up:
    cmds: 
      - task: migrate-up
      - task: dump-schema

  db-down:
    cmds:
      - task: migrate-down
      - task: dump-schema

  migrate-up:
    internal: true
    cmds:
      - echo 'Migrating up...'
      - migrate -source file://db/migrations -database $POSTGRES_URL up
    silent: true

  # migrate-up-force:
  #   cmds:
  #     - echo 'Migrating up...'
  #     - migrate -source file://db/migrations -database $POSTGRES_URL force 20241220005517
  #   silent: true

  migrate-down:
    internal: true
    cmds:
      - echo 'Migrating down...'
      - migrate -source file://db/migrations -database $POSTGRES_URL down
    silent: true

  dump-schema:
    cmds:
      - echo 'Dumping schema...'
      - pg_dump -s $POSTGRES_URL > db/schema.sql
    silent: true

  sqlc-gen:
    cmds:
      - echo 'Generating SQLC...'
      - POSTGRES_URL=$POSTGRES_URL sqlc generate
      - echo $DB_URL
    silent: true