// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/google/uuid"
)

type Pokemon struct {
	ID        uuid.UUID
	SpeciesID int32
	Level     int32
}

type PokemonStat struct {
	PokemonID uuid.UUID
	StatsID   uuid.UUID
	StatType  string
}

type SchemaMigration struct {
	Version int64
	Dirty   bool
}

type Stat struct {
	ID             uuid.UUID
	Hp             int32
	Attack         int32
	Defense        int32
	SpecialAttack  int32
	SpecialDefense int32
	Speed          int32
}
