// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

type Pokemon struct {
	ID        int32
	SpeciesID int32
	Level     int32
}

type SchemaMigration struct {
	Version int64
	Dirty   bool
}
