// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package sqlc

import (
	"context"
)

const createPokemon = `-- name: CreatePokemon :one
INSERT INTO pokemon (
    species_id, "level"
) VALUES (
    $1, $2
) RETURNING id, species_id, level
`

type CreatePokemonParams struct {
	SpeciesID int32
	Level     int32
}

func (q *Queries) CreatePokemon(ctx context.Context, arg CreatePokemonParams) (Pokemon, error) {
	row := q.db.QueryRow(ctx, createPokemon, arg.SpeciesID, arg.Level)
	var i Pokemon
	err := row.Scan(&i.ID, &i.SpeciesID, &i.Level)
	return i, err
}

const pokemonByID = `-- name: PokemonByID :one
SELECT id, species_id, level FROM pokemon WHERE id = $1
`

func (q *Queries) PokemonByID(ctx context.Context, id int32) (Pokemon, error) {
	row := q.db.QueryRow(ctx, pokemonByID, id)
	var i Pokemon
	err := row.Scan(&i.ID, &i.SpeciesID, &i.Level)
	return i, err
}
